# Generated by Django 4.1 on 2023-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_number_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('TH', 'Technician'), ('SE', 'Secretary'), ('CP', 'Project Chief'), ('IG', 'Engineer'), ('DR', 'Director'), ('NA', 'Other')], default='NA', max_length=2),
        ),
    ]
